version: 0.2

env:
  shell: bash

phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update
      - apt-get install -y npm
      - npm install -g serverless
  build:
    on-failure: ABORT
    commands:
      - |
        export BRANCH="${CODEBUILD_WEBHOOK_TRIGGER//"branch/"}"
        echo "${BRANCH}"
        if [ "${BRANCH}" = "master" ] ; then
          echo "Deploying prod"
          serverless deploy
        else
          echo "Deploying stage ${BRANCH}"
          serverless deploy --stage "${BRANCH}"
        fi
      